root: true
extends:
  - eslint:recommended
  - plugin:n/recommended
  - airbnb
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - airbnb-typescript
  - plugin:react/jsx-runtime
  - plugin:@tanstack/query/recommended
  - plugin:prettier/recommended
parserOptions:
  project:
    - './tsconfig.json'
  ecmaVersion: 2021
  sourceType: module
env:
  node: true
  browser: false
rules:
  import/extensions: 'off' # handled by TS
  import/prefer-default-export: 'off'
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: never
      pathGroups:
        - pattern: '@app/**'
          group: internal
      pathGroupsExcludedImportTypes:
        - builtin
  n/no-missing-import: 'off' # handled by TS
  '@typescript-eslint/return-await':
    - error
    - always
  '@typescript-eslint/member-ordering':
    - error
  '@typescript-eslint/no-extraneous-class':
    - error
    - allowWithDecorator: true
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - private-constructors
  '@typescript-eslint/array-type':
    - error
    - default: array-simple
      readonly: array-simple
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/boolean-prop-naming: error
  react/jsx-sort-props:
    - error
    - ignoreCase: true
      callbacksLast: true
      shorthandFirst: true
      shorthandLast: false
      noSortAlphabetically: false
      reservedFirst: true

overrides:
  - files:
      - packages/*/tests/*.ts
      - '*.spec.ts'
      - '*.test.ts'
      - vite.config.ts
    plugins:
      - vitest
    extends:
      - plugin:vitest/recommended
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
