name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'packages/**/prisma/schema.prisma') }}

      - run: yarn install --immutable
      - run: yarn prisma generate
        working-directory: packages/backend

  lint:
    needs: [install, build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'packages/**/prisma/schema.prisma') }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-common
          path: packages/common/dist

      - run: yarn run lint

  build:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'packages/**/prisma/schema.prisma') }}

      - run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-common
          path: packages/common/dist

  test:
    needs: [install, build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'packages/**/prisma/schema.prisma') }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-common
          path: packages/common/dist

      - run: yarn test

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
